
<h1>Pagina de Listar</h1>

<table class="table table-hover table-striped">
    <thead class="table-dark">
        <tr>
            <th>Titulo</th>
            <th>Categoria</th>
            <th>Descrição</th>
            <th>Preço</th>
            <th>Quantidade</th>
            <th>Foto</th>
            <th>Ações</th>
        </tr>
    </thead> 
    <tbody>
        <?php 
            foreach ($beverages as $cadaBebida) { 
                echo "
                    <tr>
                        <td>{$cadaBebida->title}</td>
                        <td>{$cadaBebida->category}</td>  
                        <td>{$cadaBebida->description}</td>
                        <td>R$ {$cadaBebida->price}</td>
                        <td>{$cadaBebida->quantity}</td>
                        <td> 
                            <a onclick='abrirFoto(this)' data-image='{$cadaBebida->id}' href='#' data-bs-toggle='modal' data-bs-target='#abrirFoto'> 
                                <img width='50px' src='{$cadaBebida->id}'>
                            </a> 
                        </td>
                        <td>
                            <a href='/editar-bebida?id={$cadaBebida->id}' class='btn btn-warning btn-sm'>Editar</a>
                            <a href='/excluir-bebida?id={$cadaBebida->id}' class='btn btn-danger btn-sm'>Excluir</a>
                        </td>
                    </tr>
                ";
            }
        ?>

        
    </tbody>
</table>


<script>
    function abrirFoto(elemento) {
        foto.setAttribute(
            'src', 
            elemento.getAttribute('data-image')
        );
    }
</script>

<!-- Modal -->
<div class="modal fade" id="abrirFoto" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <img width="100%" alt="Imagem aqui" id="foto">
      </div>
    </div>
  </div>
</div>

