<nav class="mt-5">
    <a href="/" class="btn btn-outline-dark">Inicio</a>
    <a href="/nova-bebida" class="btn btn-outline-dark">Nova Bebida</a>
    <a href="/listar-bebidas" class="btn btn-outline-dark">Listar Bebidas</a>

    <div class="dropdown d-inline">
        <button class="btn btn-outline-dark dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            Categorias
        </button>
        <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="/categorias/adicionar">Adicionar</a></li>
            <li><a class="dropdown-item" href="/categorias/listar">Listar</a></li>
        </ul>
    </div>   
</nav>
<hr>