<h1>Nova Categoria</h1>

<section class="row mt-5">
    <div class="col">
        <!-- imagem do undraw.co -->
        <img width="90%" src="/img/add.svg">
    </div>
    <div class="col">
        <article class="card card-body text-bg-dark">
            <form action="" method="post" enctype="multipart/form-data">
                <label for="name">Nome</label>
                <input id="name" name="name" type="text" class="form-control mb-3">

                <div class="d-grid">
                    <button class="btn btn-outline-light btn-lg">PRONTO</button>
                </div>
            </form>
        </article>
    </div>
</section>