<h1>Listar Categorias</h1>

<table class="table table-hover table-striped">
    <thead class="table-dark">
        <tr>
            <th>#ID</th>
            <th>Nome</th>
            <th>Ações</th>
        </tr>
    </thead> 
    <tbody>
        <?php
            foreach ($categories as $cat) {
                echo "<tr>
                    <td>{$cat->id}</td>
                    <td>{$cat->name}</td>
                    <td>
                        <a href='/categorias/editar?id={$cat->id}' class='btn btn-warning'>Editar</a>
                        <a href='/categorias/excluir?id={$cat->id}' class='btn btn-danger'>Excluir</a>
                    </td>
                </tr>";
            }
        ?>
    </tbody>
</table>